name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        uses: php-actions/composer@v6

      - name: "Run tests"
        run: composer test

  publish:
    if: contains(github.ref, 'main')
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: "Update commit status to success"
        uses: ouzi-dev/commit-status-updater@v1.1.2
        with:
          status: "success"

  publish-tag:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: "Update commit status to success"
        uses: ouzi-dev/commit-status-updater@v1.1.2
        with:
          status: "success"
